# use gmake
BINTARGET	=makebonds
DEST		=MakeBonds
LDFLAGS=-lm
CFLAGS=-O

#include /usr/local/matto/etc/Makefile
all: makebonds

# remove the following line.
PACKAGESRC	=makebonds.c Makefile README.html
include $(HOME)/src/Makefile
